"use client";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Link } from "@/i18n/routing";
import { Loader2, Mic2, Music2, Plus, ShieldCheck, Upload } from "lucide-react";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

type Voice = { id: string; name: string; description: string | null; imageUrl: string | null; status: string; verifyText: string | null; verifyUrl: string | null; voiceId: string | null; createdAt: string };
type Upload = { key: string; url: string };

async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "Request failed."); return result.data; }
async function upload(file: File, kind: "source" | "verification" | "image"): Promise<Upload> { const data = await api<{ key: string; presignedUrl: string; publicObjectUrl: string }>("/api/voices/upload", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, contentType: file.type, fileName: file.name, size: file.size }) }); const response = await fetch(data.presignedUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!response.ok) throw new Error("Upload failed."); return { key: data.key, url: data.publicObjectUrl }; }

export function VoiceLibrary() {
  const [voices, setVoices] = useState<Voice[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [style, setStyle] = useState(""); const [consent, setConsent] = useState(false);
  const [source, setSource] = useState<File | null>(null); const [image, setImage] = useState<File | null>(null); const sourceRef = useRef<HTMLInputElement>(null); const imageRef = useRef<HTMLInputElement>(null); const verificationRef = useRef<HTMLInputElement>(null);
  const load = () => api<Voice[]>("/api/voices").then(setVoices).catch((error) => toast.error(error.message));
  useEffect(load, []);
  async function create() { if (!source || !name.trim() || !consent) return toast.error("Add a name, a clean voice recording, and confirm authorization."); setBusy(true); try { const [sourceUpload, imageUpload] = await Promise.all([upload(source, "source"), image ? upload(image, "image") : Promise.resolve(null)]); await api("/api/voices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, style, sourceAudioUrl: sourceUpload.url, sourceAudioKey: sourceUpload.key, imageUrl: imageUpload?.url, imageKey: imageUpload?.key, language: "en", vocalStartS: 0, vocalEndS: 30, consent: true }) }); toast.success("Verification phrase is being prepared."); setOpen(false); setName(""); setDescription(""); setStyle(""); setSource(null); setImage(null); setConsent(false); load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to create voice."); } finally { setBusy(false); } }
  async function submitVerification(voice: Voice, file: File) { setBusy(true); try { const recording = await upload(file, "verification"); await api("/api/voices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create", id: voice.id, verifyUrl: recording.url, verificationAudioUrl: recording.url, verificationAudioKey: recording.key }) }); toast.success("Voice creation started."); load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to submit verification."); } finally { setBusy(false); } }
  return <>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-sm leading-6 text-muted-foreground">Create an authorized singing voice, verify it with a short recording, then use it in your next custom song.</p><Button className="gap-2 rounded-full" onClick={() => setOpen(true)}><Plus className="size-4" /> Add voice</Button></div>
    <input ref={verificationRef} className="hidden" type="file" accept="audio/*" onChange={(event) => { const file = event.target.files?.[0]; const id = event.currentTarget.dataset.voiceId; const voice = voices.find((item) => item.id === id); if (file && voice) submitVerification(voice, file); event.currentTarget.value = ""; }} />
    {voices.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{voices.map((voice) => <article key={voice.id} className="overflow-hidden rounded-lg border bg-white shadow-sm"><div className="relative aspect-[16/8] bg-stone-100">{voice.imageUrl ? <Image fill src={voice.imageUrl} alt={voice.name} className="object-cover" /> : <div className="grid h-full place-items-center text-stone-400"><Mic2 className="size-9" /></div>}<span className="absolute right-3 top-3 rounded-full bg-white/95 px-2.5 py-1 text-xs font-bold capitalize text-stone-700">{voice.status.replaceAll("_", " ")}</span></div><div className="p-4"><h2 className="font-bold">{voice.name}</h2><p className="mt-1 min-h-10 text-sm text-muted-foreground">{voice.description || "Personal custom singing voice"}</p>{voice.status === "ready" ? <Button asChild size="sm" className="mt-4 gap-2 rounded-full"><Link href={`/create-song?customVoice=${voice.id}`}><Music2 className="size-3.5" /> Create a song</Link></Button> : voice.status === "awaiting_recording" ? <Button size="sm" className="mt-4 gap-2 rounded-full" disabled={busy} onClick={() => { if (verificationRef.current) { verificationRef.current.dataset.voiceId = voice.id; verificationRef.current.click(); } }}><Upload className="size-3.5" /> Upload verification recording</Button> : <p className="mt-4 text-xs font-medium text-primary">We will update this voice when processing finishes.</p>}</div></article>)}</div> : <div className="mt-8 grid min-h-72 place-items-center rounded-lg border border-dashed bg-white text-center"><div><Mic2 className="mx-auto size-9 text-primary" /><h2 className="mt-3 font-bold">Your voice library is empty</h2><p className="mt-1 text-sm text-muted-foreground">Add a verified singing voice to make songs sound more like you.</p><Button className="mt-4 gap-2 rounded-full" onClick={() => setOpen(true)}><Plus className="size-4" /> Add voice</Button></div></div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>Create your singing voice</DialogTitle><DialogDescription>Use a clear, solo vocal recording. You will record a short verification phrase before the voice becomes available.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><div className="grid gap-2"><Label htmlFor="voice-name">Voice name</Label><Input id="voice-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="My singing voice" /></div><div className="grid gap-2"><Label htmlFor="voice-description">Description</Label><Textarea id="voice-description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Warm acoustic pop vocal" /></div><div className="grid gap-2"><Label htmlFor="voice-style">Style</Label><Input id="voice-style" value={style} onChange={(event) => setStyle(event.target.value)} placeholder="Pop, warm vocal" /></div><div className="grid gap-2"><Label>Source recording</Label><input ref={sourceRef} className="hidden" type="file" accept="audio/*" onChange={(event) => setSource(event.target.files?.[0] || null)} /><Button type="button" variant="outline" className="justify-start gap-2" onClick={() => sourceRef.current?.click()}><Upload className="size-4" /> {source?.name || "Upload clean vocal recording"}</Button></div><div className="grid gap-2"><Label>Cover image (optional)</Label><input ref={imageRef} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setImage(event.target.files?.[0] || null)} /><Button type="button" variant="outline" className="justify-start gap-2" onClick={() => imageRef.current?.click()}><Upload className="size-4" /> {image?.name || "Upload image"}</Button></div><label className="flex items-start gap-3 rounded-md border bg-stone-50 p-3 text-sm"><Checkbox checked={consent} onCheckedChange={(checked) => setConsent(checked === true)} /><span><ShieldCheck className="mr-1 inline size-4 text-primary" />I own this voice or have explicit permission to create and use this voice model.</span></label><Button className="gap-2" disabled={busy} onClick={create}>{busy ? <Loader2 className="size-4 animate-spin" /> : <Mic2 className="size-4" />} Start verification</Button></div></DialogContent></Dialog>
  </>;
}
